-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\majorChangeShift\modimpl_ntwk_block.vhd
-- Created: 2022-05-03 15:07:27
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: modimpl_ntwk_block
-- Source Path: majorChangeShift/ringBuffer/modimpl_ntwk
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY modimpl_ntwk_block IS
  PORT( X                                 :   IN    std_logic_vector(16 DOWNTO 0);  -- ufix17_En5
        Y                                 :   OUT   std_logic_vector(14 DOWNTO 0)  -- ufix15_En5
        );
END modimpl_ntwk_block;


ARCHITECTURE rtl OF modimpl_ntwk_block IS

  -- Signals
  SIGNAL X_unsigned                       : unsigned(16 DOWNTO 0);  -- ufix17_En5
  SIGNAL Y_tmp                            : unsigned(14 DOWNTO 0);  -- ufix15_En5

BEGIN
  X_unsigned <= unsigned(X);

  -- cgireml component
  Y_tmp <= X_unsigned(14 DOWNTO 0);

  Y <= std_logic_vector(Y_tmp);

END rtl;

